Import('BOOT_env')
Import('APP_env')
import os

WorkSpacePath = BOOT_env['WorkSpace']

length = len(WorkSpacePath)

SourcePath = os.getcwd()[length:]

BOOT_objects = BOOT_env.Object(target = [WorkSpacePath+BOOT_env['TargetPath']+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.s'], )
BOOT_objects+= BOOT_env.Object(target = [WorkSpacePath+BOOT_env['TargetPath']+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c'], )

APP_objects = APP_env.Object(target = [WorkSpacePath+APP_env['TargetPath']+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.s'], )
                     #CPPPATH = Split(WorkSpacePath+SourcePath))
APP_objects+= APP_env.Object(target = [WorkSpacePath+APP_env['TargetPath']+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c'], )
                     #CPPPATH = [WorkSpacePath+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Include/',
                     #                WorkSpacePath+SourcePath+'/CMSIS/Include/'])



Return('BOOT_objects','APP_objects')