Import('env')
import os

WorkSpacePath = env['WorkSpace']

length = len(WorkSpacePath)

SourcePath = os.getcwd()[length:]

objects = env.Object(target = [WorkSpacePath+'/Build/obj'+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.s'], )
                     #CPPPATH = Split(WorkSpacePath+SourcePath))
objects+= env.Object(target = [WorkSpacePath+'/Build/obj'+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx'] , 
                     source = ['CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c'], )
                     #CPPPATH = [WorkSpacePath+SourcePath+'/CMSIS/Device/ST/STM32F4xx/Include/',
                     #                WorkSpacePath+SourcePath+'/CMSIS/Include/'])


# print('Compile',objects)
Return('objects')