
# project defines
BOOT_CPPDEFINES = [
   # 'STM32F407xx',
   'STM32F407VE',
   'STM32F4XX',
   'USE_STDPERIPH_DRIVER',
   '__ASSEMBLY__',
   '__FPU_USED',
   ]
APP_CPPDEFINES = BOOT_CPPDEFINES