Import('BOOT_env')
Import('APP_env')
import os

WorkSpacePath = APP_env['WorkSpace']
length = len(WorkSpacePath)
SourcePath = os.getcwd()[length:]
BOOT_objects = []

APP_objects = APP_env.Object(target = [APP_env['TargetPath']+SourcePath+'/display'] , source = ['display.c'] , CPPPATH = Split(WorkSpacePath+'/Source/')) #


Return('BOOT_objects','APP_objects')
